add logic for winner | for show Player & his suit
yegorgangalo/Andersen-X-O pull request #1
Opened 2021-03-15 15:30 UTC by yegorgangalo

2021-03-16 06:09 UTC, EugeneSolovyev requested changes

2021-03-16 06:09 UTC, EugeneSolovyev commented on src/css/_xo-field.scss
> -  //   border-radius: 10px;
удаляй неиспользуемый код
это касается всего, как css/html так и js
поскольку в 99% случаев ты его больше не будешь использовать

2021-03-16 06:09 UTC, EugeneSolovyev commented on build/index.html
> +<!doctype html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta http-equiv="X-UA-Compatible" content="ie=edge"/><title>XO</title>
папку build надо закинуть в gitignore

2021-03-16 06:09 UTC, EugeneSolovyev commented on src/js/components/TicTacToe.js
> +        return this.clickCount % 2 ? true : false;
можно явно привести к булину и не использовать тернарник
```js
return Boolean(this.clickCount % 2)
```

2021-03-16 06:09 UTC, EugeneSolovyev commented on src/js/components/TicTacToe.js
> +            : (this.PLAYER2.victory += 1, this.refs.spanScoreVictory2Ref.textContent = this.PLAYER2.victory);
вот тут плохо читается код
либо используй if/else
либо попробуй вынести в отдельный метод

2021-03-16 06:09 UTC, EugeneSolovyev commented on src/js/components/TicTacToe.js
> +            : (playerName.textContent = this.PLAYER1.name, playWith.textContent = this.PLAYER1.suit)
то же самое и тут, плохо читается

2021-03-16 06:09 UTC, EugeneSolovyev commented on src/js/components/TicTacToe.js
> +    }
ох, вот тут совсем плохо
1) у тебя использются if внутри case
2) выражения внутри if у тебя максимально длинные
тут придется подумать как сделать лучше и порефакторить

* по сути у нас что для X, что для O, выйгрышные позиции одинаковые
и могут быть записаны как константы
* в этот метод можно было бы передавать игрока или его выбранные ячейки
* так же думаю удобно было бы работать с позициями как если бы это были матрицы (можно было бы использовать двумерный массив, типа как ниже
```
[
[true, false, false],
[true, true, false]
[false, false, true]
]
```
тогда бы обход и поиск позиций был бы локаничней, даже при условии что сложность алгоритма была бы квадратичной `O(n^2)`

2021-03-16 06:09 UTC, EugeneSolovyev commented on src/js/components/TicTacToe.js
> +        PlayFirstSuit = "X",
как правило переменные (а равно и ключи в объекте) пишутся в camelCase
PascalCase используется для именования классов

2021-03-16 11:41 UTC, EugeneSolovyev requested changes

2021-03-16 11:41 UTC, EugeneSolovyev commented on src/js/components/TicTacToe.js
> +        return refs;
```js
return {
  spanPlayerNameRef: playField.querySelector('[player-name]'),
  spanPlayWithRef: playField.querySelector('[play-with-xo]'),
  //... rest fields
}
```

тут просто нет необходимости в самой константе, т.к. ты просто тут заполняешь объект refs

2021-03-16 11:41 UTC, EugeneSolovyev commented on src/js/components/TicTacToe.js
> +    putMarkInCell(event) {
тут можно деструктурировать до `textContent`

```js
putMarkInCell({ target: { textContent } }) {
  if (textContent !== '') return;
  //... rest logic here....
}
```

2021-03-16 11:41 UTC, EugeneSolovyev commented on src/js/components/TicTacToe.js
> +    isWinner(markedCell) {
деструктурируй, бо `markedCell` тебе нужен только для получения айдишки

2021-03-16 11:41 UTC, EugeneSolovyev commented on src/js/components/TicTacToe.js
> +    }
смотри, как я понимаю так ты отошел от О(н^2)
но создал много мелких методов которых можно было не. создавать, если бы ты придерживался того подхода который я предложил
может попробуем сделать через вложенный цикл?

2021-03-16 11:41 UTC, EugeneSolovyev commented on src/js/components/TicTacToe.js
> +        const secondCell = cells[firstCellIndex + gap].textContent;
такую логику я просто повесил бы на изменения html
т.е. на верхний элемент и слушал бы событие click

2021-03-16 11:49 UTC, yegorgangalo commented on src/js/components/TicTacToe.js
> +    putMarkInCell(event) {
Я использую в 48 строке
const currentCell = event.target;
this.isWinner(currentCell)

Вопрос: 'вложенная деструктуризация' -  это хорошая практика?

2021-03-16 11:51 UTC, yegorgangalo commented on src/js/components/TicTacToe.js
> +        return refs;
В самом деле. Спасибо. исправил

2021-03-16 11:53 UTC, yegorgangalo commented on src/js/components/TicTacToe.js
> +    }
Переделаю. Без проблем. 
Я показал свой вариант. Теперь реализую твой)

2021-03-16 12:18 UTC, yegorgangalo commented on src/js/components/TicTacToe.js
> +        const secondCell = cells[firstCellIndex + gap].textContent;
Всплытие событий. Я вообще об этом забыл. Спасибо.
26 строка: this.refs.playCellCollection.forEach(cell => cell.addEventListener('click', this.putMarkInCell.bind(this)));
В идеале вместо вешания 9 событий на каждую ячейку я повешаю его на родителя.
и вешать нужно функцию putMarkInCell, верно?

2021-03-17 06:41 UTC, EugeneSolovyev commented on src/js/components/TicTacToe.js
> +    putMarkInCell(event) {
вложенная дестуктуризация - это ок
главное чтобы не упало по пути
но как правила для объектов класса Event такого не происходит, главное тянуть проперти которые там присутствуют
здесь как раз твой случай

2021-03-17 06:41 UTC, EugeneSolovyev commented on src/js/components/TicTacToe.js
> +    }
тебе будет же проще потом =)

2021-03-17 09:47 UTC, yegorgangalo commented on src/js/components/TicTacToe.js
> +    putMarkInCell(event) {
Я смог сделать только вот так:
putMarkInCell = ({ target }) => {
        const { id, textContent, tagName } = target;
        if ( tagName !== 'TD' || textContent !== '') {
            return;
        }
        this._clickCount += 1;
        target.textContent = this.clickIsOdd() ? this.PLAYER1.suit : this.PLAYER2.suit;
        this.isWinner(id) && this.endGame();
        this.changePlayer();
    }
    
    Если я сразу делаю вложенную деструктуризацию, то переменной target не существует. ВОт ошибка в консоли: Uncaught ReferenceError: target is not defined
    putMarkInCell = ({ target: { id, textContent, tagName } }) => {
        if ( tagName !== 'TD' || textContent !== '') {
            return;
        }
        this._clickCount += 1;
        target.textContent = this.clickIsOdd() ? this.PLAYER1.suit : this.PLAYER2.suit;
        this.isWinner(id) && this.endGame();
        this.changePlayer();
    }

2021-03-17 12:10 UTC, EugeneSolovyev requested changes

2021-03-17 12:10 UTC, EugeneSolovyev commented on src/js/components/TicTacToe.js
> +            return isWin;
нет смысла в константе, просто сразу возвращай значение
то же и для кода ниже в этом методе

2021-03-17 12:15 UTC, yegorgangalo commented on src/js/components/TicTacToe.js
> +            return isWin;
Done

2021-03-17 12:18 UTC, merged